name: wind-farms

channels:
  - conda-forge
  - fastai
  
dependencies:
  - python=3.7
  - pandas
  - geopandas
  - matplotlib
  - jupyterlab
  - seaborn
  - mkdocs
  - mkdocs-material
  - python-dotenv
  - dagster
  - lxml
  - typer
  - pip
  
  - pip:
      - -e .
      - nbdev
      - ipypb
      - feautils
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix